var hsts = require("./hsts");
var ss = require("sdk/simple-storage");
var data = require("sdk/self").data;

function readHosts() {
  // get a list of hosts with simple https everywhere rules.
  // generated by utils/simple.py
  return data.load('hosts.txt').split(' ');
}

ss.storage.hstsOn = false;
ss.storage.hstsHosts = readHosts();

function toggleHsts() {
  if (!ss.storage.hstsOn) {
    while (ss.storage.hstsHosts.length > 0) {
      var host = ss.storage.hstsHosts.pop();
      hsts.add(host, false);
      console.log("Adding HSTS host: "+host);
    }
    ss.storage.hstsOn = true;
  } else {
    hosts = readHosts();
    while (hosts.length > 0) {
      var host = hosts.pop();
      hsts.clear(host, false);
      ss.storage.hstsHosts.push(host);
      console.log("Removing HSTS host: "+host);
    }
    ss.storage.hstsOn = false;
  }
}

var widget1 = require("sdk/widget").Widget({
  id: "hsts-start",
  label: "HSTS Everyhere Start",
  contentURL: "https://www.mozilla.org/favicon.ico",
  onClick: toggleHsts,
  tooltip: "Click to turn custom HSTS on/off!"
});
